version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MLBdb
    ports:
      - '3306:3306'
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './apps/MLB-backend/public/:/home/www/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/MLB-backend/:/home/www/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000